import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "600", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <nav>
          <Navbar></Navbar>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
